### ISSUE TITLE
What is the license for this repository?

### ISSUE THREAD

**Issue by andrericardo** [timschreiber/DapperUnitOfWork#13]
@timschreiber your repository is a really clear explanation of unit of work and I would like to use parts of it. 

What is the license this code is under?

**Comment by fdonnet** [comment]
hi @andrericardo , I don't know if Tim will return one day but if you are interested you can try my generator : https://github.com/fdonnet/Dapper-Layers-Generator. It doesn't full implement unitofwork but a strong dbcontext and a minimal dbcontextfactory. 

You give a MySql information_schema to read to the generator prog and it will generate all the base dapper code you need to begin with your app. So you can focus on the real functions and complex queries you need to produce.

It's an alpha, open source, you can use it for all uses. If you upgrade some parts, don't hesitate to PR.

The goal is to be independent from other libs (paid) and go with a full generated DAL layer that you can extend to your need.

If Tim would like to have a look in the dbcontext generator it can be great.

**Comment by timschreiber** [comment]
> @timschreiber your repository is a really clear explanation of unit of work and I would like to use parts of it.
> 
> What is the license this code is under?

This repo was created for a tutorial and is by no means a complete solution. But I license almost everything else under the MIT license, so I will update the repo to use the MIT license as well.

**Comment by andrericardo** [comment]
@fdonnet Thanks for sharing your project, at the moment I don't have the need for it, but if I do in the future will have a look.

@timschreiber thank you for adding the license, closing the issue now.
